name: Build GSI

on:
    workflow_dispatch:
        inputs:
            ROM_URL:
                description: 'ROM_URL'
                required: true
                default: 'https://github.com/FoxetGSI/Builds/releases/download/06is1527/Generic-AB-13-2025-06-02-FoxetGSI.7z'
            ROM_TYPE:
                description: 'ROM Type'
                required: true
                type: choice
                options: 
                - Generic
                - Pixel
                - HyperOS
                - OneUI
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - name: Download & Patch
          run: |
                #sudo apt update && sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename liblzma-dev python-pip brotli lz4 protobuf-compiler git gawk
                git clone https://github.com/defnotegor/OriginGSITool/ && cd OriginGSITool
                mkdir -p DownloadedROMs
                mkdir -p UnpackedROMs
                mkdir -p UnpackedROMs/system                
                sudo bash LinkToGSI.sh "${{github.event.inputs.ROM_URL}}" ${{github.event.inputs.ROM_TYPE}}
                7z a -v500m -tzip FoxetGSIROM.zip Output/*.img
        - name: Upload to Release
          uses: softprops/action-gh-release@v1
          with:
            files: | 
              OriginGSITool/FoxetGSIROM.*
              OriginGSITool/Output/FoxetGSIROM.*
            name: FoxetGSI-${{ github.run_id }}
            tag_name: ${{ github.run_id }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
